### ISSUE TITLE
Feature Request: OBJ Import support for Map Editor

### ISSUE THREAD

**Issue by mixxit** [mixxit/EQ2ModelViewer#1]
See this for details:

http://cutpon.com:3000/devn00b/EQ2EMu/issues/445

**Comment by mixxit** [comment]
Bounty posted: https://app.bountysource.com/issues/109640853-feature-request-obj-import-support-for-map-editor

**Comment by mixxit** [comment]
Cant use bounty source on eq2emu server so made fork here

**Comment by KN4CK3R** [comment]
The Discord link does not work or is private.

**Comment by mixxit** [comment]
> The Discord link does not work or is private.

https://discord.com/invite/jh5gMVBe?utm_source=Discord%20Widget&utm_medium=Connect
